Repository subscriptionRescueTeam/save-my-youth, pull requests merged in 2022-05, with the labels that each got.

#4 Feat: 청약 좋아요 갯수 구현
  package-lock.json
  src/components/Header/index.tsx
Labels: enhancement

#16 Docs: issue, pull request 탬플릿 추가
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#12 Feat: 메인 페이지 헤더 구현
  package-lock.json
  package.json
  src/App.tsx
  src/components/Header/index.styled.ts
  src/components/Header/index.tsx
  src/components/Icon/index.styled.ts
  src/components/Icon/index.tsx
  src/components/IconMenu/index.tsx
  src/components/LayoutNavigation/index.styled.ts
  src/components/LayoutNavigation/index.tsx
  src/pages/Home/index.tsx
Labels: enhancement

#23 Feat: 마이페이지 유저 정보 구현
  src/App.tsx
  src/pages/Mypage/index.tsx
Labels: enhancement

#22 Feat: 검색페이지 레이아웃 구현
  .gitignore
  src/App.tsx
  src/pages/Home/index.tsx
  src/pages/Search/index.tsx
  src/types/index.tsx
Labels: enhancement

#24 Feat: 사이드바 구현
  src/components/Header/index.styled.ts
  src/components/Header/index.tsx
  src/components/LayoutNavigation/index.tsx
  src/components/Sidebar/index.tsx
Labels: enhancement

#25 Feat: 마이페이지 고객센터 정보 구현
  src/App.tsx
  src/components/ServiceMenu/index.tsx
  src/pages/Mypage/index.tsx
Labels: enhancement

#29 Feat: 컬러 정의
  src/constants/color.ts
  src/constants/index.ts
Labels: 프론트

#42 Feat: 마이페이지 리뉴얼
  src/components/ServiceMenu/index.tsx
  src/pages/Mypage/index.tsx
  src/types/index.ts
  tsconfig.json
Labels: 프론트, 유아이

#43 Fix: 메인 페이지 헤더와 사이드바 수정
  package-lock.json
  src/App.tsx
  src/asset/ArrowDown.tsx
  src/asset/ArrowLeft.tsx
  src/asset/ArrowRight.tsx
  src/asset/ArrowUp.tsx
  src/asset/index.ts
  src/components/Header/index.tsx
  src/components/Input/index.tsx
  src/components/LayoutNavigation/index.tsx
  src/components/MainCardItem/index.tsx
  src/components/Sidebar/OptionItem/index.tsx
  src/components/Sidebar/OptionList/index.tsx
  src/components/Sidebar/index.tsx
Labels: 버그

#48 Fix:불필요한 styled icon제거
  src/asset/searchicon.tsx
  src/components/Header/index.tsx
  src/pages/Search/index.tsx
  src/pages/Search/list.tsx
  src/utils/api.tsx
Labels: 프론트

#52 Chore: 패키지 재정비
  package-lock.json
  package.json
Labels: 버그, 문서, 프론트

#59 Hotfix: 경고 제거
  src/asset/Alarm.tsx
  src/asset/ArrowDown.tsx
  src/asset/ArrowLeft.tsx
  src/asset/ArrowRight.tsx
  src/asset/ArrowUp.tsx
  src/asset/Hamburger.tsx
  src/asset/Location.tsx
  src/asset/Search.tsx
  src/asset/searchicon.tsx
  src/pages/Search/index.tsx
Labels: 버그, 프론트, 핫픽스

#56 Feat: 검색리스트 스타일
  src/pages/Search/index.tsx
Labels: 프론트

#60 Feat: 헤더 뒤로가기 기능 구현
  src/asset/ArrowLeft.tsx
  src/components/CommonHeader/index.tsx
  src/components/ServiceMenu/index.tsx
  src/pages/Detail/index.tsx
  src/pages/Mypage/index.tsx
Labels: 프론트

#61 Fix: 웹에서 서치페이지 안보이는 부분 수정
  src/pages/Search/index.tsx
Labels: 버그, 프론트

#62 Feat: 사이드바 애니메이션
  src/components/Header/index.tsx
  src/components/Input/index.tsx
  src/pages/Home/index.tsx
Labels: 프론트, 유아이

#63 Feat: 검색페이지에 헤더 적용
  src/components/SearchHeader/index.tsx
  src/pages/Search/index.tsx
Labels: 버그, 프론트

#65 Refactor: 검색페이지 리뉴얼
  src/pages/Search/index.tsx
Labels: 프론트, 유아이

#83 !HOTFIX: 버그 수정
  src/App.tsx
  src/asset/picture2.png
  src/components/Card/index.tsx
  src/components/CardSlider/index.tsx
  src/components/Input/index.tsx
  src/components/MainCardItem/index.tsx
  src/pages/Detail/index.tsx
Labels: 버그, 문서, 프론트, 유아이, 핫픽스

#88 Fix: Sidebar
  src/App.tsx
  src/asset/Close.tsx
  src/asset/index.ts
  src/components/CardSlider/index.tsx
  src/components/Header/index.tsx
  src/components/LayoutNavigation/index.tsx
  src/components/Sidebar/OptionList/index.tsx
  src/components/Sidebar/index.tsx
  src/components/Title/index.tsx
  src/components/index.ts
  src/pages/Home/index.tsx
Labels: 버그, 프론트, 유아이

#85 Feat: 마이페이지 카테고리 페이지 추가
  src/App.tsx
  src/pages/AlarmSetting/index.tsx
  src/pages/Like/index.tsx
  src/pages/ServiceCenter/index.tsx
  src/pages/UserModify/index.tsx
Labels: 프론트

#93 Feat: recoil 추가
  src/atom/userAtom.tsx
  src/main.tsx
Labels: 프론트

#99 Hotfix: 배포 해결
  src/components/ServiceMenu/index.tsx
Labels: 버그, 핫픽스

#100 Rename: 백엔드 폴더 병합
  backend/.dockerignore
  backend/.gitignore
  backend/.vscode/settings.json
  backend/Dockerfile
  backend/LICENSE
  backend/Procfile
  backend/README.md
  backend/home/__init__.py
  backend/home/migrations/0001_initial.py
  backend/home/migrations/0002_create_homepage.py
  backend/home/migrations/__init__.py
  backend/home/models.py
  backend/home/static/css/welcome_page.css
  backend/home/templates/home/home_page.html
  backend/home/templates/home/welcome_page.html
  backend/manage.py
  backend/requirements.txt
  backend/runtime.txt
  backend/save_my_youth/__init__.py
  backend/save_my_youth/api.py
  backend/save_my_youth/settings/__init__.py
  backend/save_my_youth/settings/base.py
  backend/save_my_youth/settings/dev.py
  backend/save_my_youth/settings/production.py
  backend/save_my_youth/static/css/save_my_youth.css
  backend/save_my_youth/static/js/save_my_youth.js
  backend/save_my_youth/templates/404.html
  backend/save_my_youth/templates/500.html
  backend/save_my_youth/templates/base.html
  backend/save_my_youth/urls.py
  backend/save_my_youth/wsgi.py
  backend/search/__init__.py
  backend/search/templates/search/search.html
  backend/search/views.py
  backend/subscription/__init__.py
  backend/subscription/admin.py
  backend/subscription/api.py
  backend/subscription/apps.py
  backend/subscription/migrations/0001_initial.py
  backend/subscription/migrations/0002_alter_subscription_date.py
  backend/subscription/migrations/__init__.py
  backend/subscription/models.py
  backend/subscription/schema.py
  backend/subscription/tests.py
  backend/subscription/views.py
  backend/user/__init__.py
  backend/user/admin.py
  backend/user/api.py
  backend/user/apps.py
  backend/user/migrations/0001_initial.py
  backend/user/migrations/__init__.py
  backend/user/models.py
  backend/user/schema.py
  backend/user/tests.py
  backend/user/views.py
Labels: 문서

#103 Feat: TabBar 컴포넌트 추가
  frontend/src/components/TabBar/index.tsx
  frontend/src/components/index.ts
  frontend/src/pages/Detail/index.tsx
Labels: 프론트, 유아이

#109 Feat: 사이드바 라우팅
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/components/Sidebar/index.tsx
Labels: 프론트엔드

#107 Fix: 메인 아이콘 수정
  frontend/src/asset/ExclamationPoint.tsx
  frontend/src/asset/index.ts
  frontend/src/components/Header/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/LayoutNavigation/index.tsx
  frontend/src/components/MainCardItem/index.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/types/index.ts
  frontend/src/types/index.tsx
  package-lock.json
Labels: 버그, 프론트엔드, 유아이

#112 Feat: 로그인 기능 및 라우팅 연동
  frontend/src/App.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/index.ts
Labels: 프론트엔드

#116 Fix: TabBar 커스텀
  frontend/src/components/TabBar/index.tsx
Labels: 프론트엔드, 유아이

#122 Fix: 타입명 변경
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/MainCardItem/index.tsx
  frontend/src/components/MainCardList/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드

#130 Feat: 구글 로그인 백엔드 연동완료
  backend/save_my_youth/api.py
  backend/save_my_youth/settings/base.py
  backend/user/api.py
  frontend/src/pages/Login/index.tsx
  frontend/src/utils/axiosInstance.tsx
Labels: 프론트엔드, 백엔드

#132 Hotfix: 검색 api 연동 오류
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/asset/Alarm.tsx
  frontend/src/asset/ArrowDown.tsx
  frontend/src/asset/ArrowLeft.tsx
  frontend/src/asset/ArrowRight.tsx
  frontend/src/asset/ArrowUp.tsx
  frontend/src/asset/BlueHeart.tsx
  frontend/src/asset/Close.tsx
  frontend/src/asset/ExclamationPoint.tsx
  frontend/src/asset/Hamburger.tsx
  frontend/src/asset/Location.tsx
  frontend/src/asset/Search.tsx
  frontend/src/asset/index.ts
  frontend/src/assets/icons/alarm.svg
  frontend/src/assets/icons/arrowDown.svg
  frontend/src/assets/icons/arrowLeft.svg
  frontend/src/assets/icons/arrowRight.svg
  frontend/src/assets/icons/arrowUp.svg
  frontend/src/assets/icons/blueHeart.svg
  frontend/src/assets/icons/close.svg
  frontend/src/assets/icons/exclamationPoint.svg
  frontend/src/assets/icons/hamburger.svg
  frontend/src/assets/icons/location.svg
  frontend/src/assets/icons/search.svg
  frontend/src/assets/images/favicon.png
  frontend/src/assets/images/picture.png
  frontend/src/assets/images/picture2.png
  frontend/src/assets/images/save_my_youth_image.png
  frontend/src/components/Card/index.tsx
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/CommonHeader/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/SaleSchedule/index.tsx
  frontend/src/components/SearchHeader/index.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/components/Sidebar/OptionList/index.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/index.d.ts
  frontend/src/pages/Detail/index.tsx
  frontend/src/pages/Search/index.tsx
  frontend/vite.config.ts
Labels: 버그, 프론트엔드, 이슈, 핫픽스

#137 Feat: 404 페이지 추가
  frontend/src/App.tsx
  frontend/src/assets/images/errorNotFound.gif
  frontend/src/index.d.ts
  frontend/src/pages/NotFound/index.tsx
  frontend/src/pages/index.ts
Labels: 프론트엔드

#135 Fix: 메인 페이지 카드 슬라이더
  frontend/src/components/Card/index.tsx
  frontend/src/components/CardSlider/index.tsx
  frontend/src/types/index.ts
Labels: 버그, 프론트엔드, 유아이

#153 Fix: 충돌 해결! (매직타로 부분)
  frontend/src/components/SearchCard/index.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/useSearch.tsx
  frontend/src/types/index.ts
  frontend/src/utils/api.tsx
Labels: 버그, 프론트엔드, 핫픽스

#156 Style: 고객센터 내용 추가
  frontend/src/App.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/pages/Help/index.tsx
  frontend/src/pages/ServiceCenter/index.tsx
  frontend/src/pages/index.ts
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#162 Fix: Google 로그인 연동 오류 해결
  backend/save_my_youth/api.py
  backend/save_my_youth/settings/base.py
  backend/save_my_youth/urls.py
  backend/subscription/schema.py
  backend/user/api.py
  backend/user/schema.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Login/index.tsx
  frontend/src/utils/axiosInstance.tsx
Labels: 버그, 프론트엔드, 핫픽스, 백엔드

#164 Feat: 메인 페이지 API 연결
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/MainCardItem/index.tsx
  frontend/src/components/MainCardList/index.tsx
  frontend/src/hooks/useTheOtherDaySubscription.tsx
  frontend/src/hooks/useTodaySubscription.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드

#159 Fix: 검색목록 구현
  frontend/src/components/SearchCard/index.tsx
  frontend/src/components/SearchCardItem/index.tsx
  frontend/src/components/SearchCardList/index.tsx
  frontend/src/components/SearchSortButton/index.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#165 Feat: Accordion
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#171 Refactor: 컨벤션 맞추기
  frontend/src/components/Card/index.tsx
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/CommonHeader/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Icon/index.tsx
  frontend/src/components/LayoutCenter/index.tsx
  frontend/src/components/MainCardItem/index.tsx
  frontend/src/components/MainCardList/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/types/index.ts
Labels: 버그, 프론트엔드

#174 Refactor: SearchCardItem 컴포넌트 코드 리팩토링
  frontend/src/components/SearchCardItem/index.tsx
  frontend/src/pages/Like/index.tsx
  frontend/src/pages/Search/index.tsx
  package-lock.json
Labels: 프론트엔드, 유아이

#175 Refactor: 프론트엔드 Refresh토큰 로직 수정, 백엔드 API 로직 리팩토링
  backend/requirements.txt
  backend/save_my_youth/api.py
  backend/save_my_youth/settings/base.py
  backend/subscription/admin.py
  backend/subscription/api.py
  backend/subscription/apps.py
  backend/subscription/migrations/0003_alter_subscription_options_and_more.py
  backend/subscription/migrations/0004_subscription_expiry.py
  backend/subscription/models.py
  backend/subscription/operator.py
  backend/subscription/schema.py
  backend/subscription/views.py
  backend/user/api.py
  backend/user/schema.py
  frontend/src/pages/Login/index.tsx
  frontend/src/utils/axiosInstance.tsx
Labels: 버그, 프론트엔드, 백엔드

#176 Style: 메인 페이지 카드
  frontend/src/components/Card/index.tsx
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/ListTitle/index.tsx
  frontend/src/components/TodaySubscriptionNull/index.tsx
  frontend/src/hooks/useTodaySubscription.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#178 Refactor: 중간 점검
  frontend/src/components/Card/index.tsx
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/CommonHeader/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/InputLabel/index.tsx
  frontend/src/components/ListTitle/index.tsx
  frontend/src/components/MainCardList/index.tsx
  frontend/src/components/SearchCardList/index.tsx
  frontend/src/components/SearchHeader/index.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/components/Sidebar/OptionList/index.tsx
  frontend/src/components/TabBar/index.tsx
  frontend/src/components/UserInfo/index.tsx
  frontend/src/hooks/useSearch.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/pages/Like/index.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/types/index.ts
  frontend/src/utils/axiosInstance.tsx
Labels: 버그, 문서, 프론트엔드, 이슈

#184 Feat: Mobile only
  frontend/src/GlobalStyle.ts
  frontend/src/components/LayoutNavigation/index.tsx
Labels: 프론트엔드, 유아이

#189 Feat: 로그인, 로그아웃
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/components/Sidebar/OptionList/index.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/main.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드

#190 Feat: 좋아요 페이지 구현
  frontend/src/pages/Like/index.tsx
Labels: 프론트엔드, 유아이

#191 Feat:검색결과 건수 구현
  frontend/src/components/LatestSearchSortButton/index.tsx
  frontend/src/components/PopularSearchButton/index.tsx
  frontend/src/components/SearchCardItem/index.tsx
  frontend/src/components/SearchCardList/index.tsx
  frontend/src/components/SearchSortButton/index.tsx
  frontend/src/hooks/usePopularity.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#193 Feat: Faq 모델링, api 구현
  backend/customer_service/__init__.py
  backend/customer_service/admin.py
  backend/customer_service/api.py
  backend/customer_service/apps.py
  backend/customer_service/migrations/0001_initial.py
  backend/customer_service/migrations/0002_faqcategory_faq_faq_category.py
  backend/customer_service/migrations/0003_alter_faq_answer_alter_faq_faq_category_and_more.py
  backend/customer_service/migrations/__init__.py
  backend/customer_service/models.py
  backend/customer_service/schema.py
  backend/customer_service/tests.py
  backend/customer_service/views.py
  backend/save_my_youth/api.py
  backend/save_my_youth/settings/base.py
  backend/user/views.py
Labels: 백엔드

#194 Hotfix: 로그인 하지 않았을 때 사이드바 다르게 표현
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/CommonHeader/index.tsx
  frontend/src/components/LayoutNavigation/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/components/Sidebar/OptionList/index.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Mypage/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이, 핫픽스

#197 Feat: 메인 페이지 큰 배너
  frontend/src/assets/images/mainBanner.svg
  frontend/src/pages/Home/index.tsx
Labels: 프론트엔드, 유아이

#199 Feat: 메인 페이지 작은 배너
  frontend/src/assets/icons/arrowRight.svg
  frontend/src/assets/icons/arrowRight.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/pages/Home/index.tsx
Labels: 프론트엔드, 유아이

#201 Feat: FAQ
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/hooks/useFAQ.tsx
  frontend/src/pages/Help/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드

#204 Fix: 로그인 화면 오류 수정
  frontend/src/components/LayoutCenter/index.tsx
  frontend/src/pages/Login/index.tsx
Labels: 버그, 프론트엔드

#206 Feat: 상세페이지 일정 추가
  frontend/src/components/DetailLocation/index.tsx
  frontend/src/components/DetailSchedule/index.tsx
  frontend/src/components/SearchCardList/index.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/pages/Like/index.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드

#208 Chore: 전체 최적화 작업
  frontend/.eslintrc
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/arrowRight.svg
  frontend/src/assets/icons/arrowRight.tsx
  frontend/src/components/Accordion/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/ServiceMenu/index.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/hooks/useFAQ.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/pages/Help/index.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/types/index.ts
Labels: 문서, 프론트엔드

#215 Refactor: Backend 코드 리팩토링, API 설명 추가, ReadMe 파일 수정
  README.md
  backend/save_my_youth/settings/base.py
  backend/subscription/api.py
  backend/subscription/schema.py
  backend/user/api.py
  backend/user/schema.py
Labels: 버그, 백엔드

#219 !HOTFIX: 사용자 이름이 unique 값으로 들어가는 문제 해결
  backend/user/api.py
  backend/user/schema.py
  frontend/src/components/CardSlider/index.tsx
Labels: 핫픽스, 백엔드

#223 Fix: Cors 재 설정 수정
  backend/save_my_youth/settings/base.py
Labels: 버그, 백엔드

#221 Feat: 서비스 소개 페이지
  frontend/src/App.tsx
  frontend/src/assets/icons/gitHub.svg
  frontend/src/assets/images/team.png
  frontend/src/components/CardSlider/index.tsx
  frontend/src/components/ServiceInfo/index.tsx
  frontend/src/components/TabBar/index.tsx
  frontend/src/components/TeamInfo/index.tsx
  frontend/src/hooks/useTodaySubscription.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Info/index.tsx
  frontend/src/pages/index.ts
Labels: 프론트엔드

#229 Feat: footer 생성
  frontend/src/App.tsx
  frontend/src/assets/images/footer.png
  frontend/src/components/Footer/index.tsx
  frontend/src/pages/Home/index.tsx
Labels: 프론트엔드, 유아이

#231 Fix: user like api 500에러 수정
  backend/subscription/api.py
Labels: 버그, 백엔드

#213 Feat: type 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LatestSearchSortButton/index.tsx
  frontend/src/components/PopularSearchButton/index.tsx
  frontend/src/components/SearchCardItem/index.tsx
  frontend/src/components/SearchCardList/index.tsx
  frontend/src/hooks/useLatest.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#238 Fix: same key in footer
  frontend/src/components/Footer/index.tsx
Labels: 버그, 프론트엔드

#240 Fix: kako 로그인
  frontend/package-lock.json
  frontend/package.json
  frontend/src/constants/palette.ts
  frontend/src/pages/Login/index.tsx
Labels: 버그, 프론트엔드, 백엔드
