Repository subscriptionRescueTeam/save-my-youth, pull requests merged in 2022-06, with the labels that each got.

#243 Refactor: 상세페이지 추가 작업
  frontend/src/components/TabBar/index.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드

#244 Feat: debounce 적용&key propserror 해결
  frontend/src/components/SearchCardList/index.tsx
  frontend/src/hooks/useDebounce.tsx
  frontend/src/pages/Search/index.tsx
Labels: 버그, 유아이

#246 Refactor: detailcustom
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Detail/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드

#257 Fix: 청약 가져오는 훅 하나로 통합
  frontend/src/hooks/useSubscription.tsx
  frontend/src/hooks/useTheOtherDaySubscription.tsx
  frontend/src/hooks/useTodaySubscription.tsx
  frontend/src/pages/Home.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드

#258 Fix: 청약 가져오는 훅 통합 (useSearch까지)
  frontend/src/hooks/useSearch.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Search.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 백엔드

#259 Refactor: 검색어 없을 경우에 메세지&placeholder 수정
  frontend/src/hooks/usePopularity.tsx
  frontend/src/pages/Search.tsx
Labels: 프론트엔드, 유아이

#261 Fix: 상세 페이지 API 연동
  frontend/src/components/DetailSchedule.tsx
  frontend/src/components/MainCardItem.tsx
  frontend/src/components/MainCardList.tsx
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Home.tsx
  frontend/src/types/index.ts
Labels: 버그, 프론트엔드, 백엔드

#263 Feat: 인기 청약, 최신 청약 보여주기
  frontend/src/App.tsx
  frontend/src/components/CardSlider.tsx
  frontend/src/components/CommonHeader.tsx
  frontend/src/components/Item.tsx
  frontend/src/components/List.tsx
  frontend/src/components/ListTitle.tsx
  frontend/src/components/MainCardList.tsx
  frontend/src/components/SearchCardItem.tsx
  frontend/src/components/SearchCardList.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/More.tsx
  frontend/src/pages/index.ts
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이, 백엔드

#267 Style: 메인 페이지 인기, 최신 청약 디자인 변경
  frontend/src/components/Card.tsx
  frontend/src/components/CardSlider.tsx
  frontend/src/components/CommonHeader.tsx
  frontend/src/components/Description.tsx
  frontend/src/components/Indexing.tsx
  frontend/src/components/Item.tsx
  frontend/src/components/List.tsx
  frontend/src/components/ListTitle.tsx
  frontend/src/components/SearchCardItem.tsx
  frontend/src/components/SearchCardList.tsx
  frontend/src/components/TodaySubscriptionNull.tsx
  frontend/src/constants/variables.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/More.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#269 Refactor: Eslint, declare 설정
  frontend/.eslintrc
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LatestSearchSortButton.tsx
  frontend/src/components/LayoutCenter.tsx
  frontend/src/components/PopularSearchButton.tsx
  frontend/src/components/index.ts
  frontend/src/hooks/useLike.tsx
  frontend/src/pages/Like.tsx
  frontend/src/pages/Search.tsx
  frontend/src/types/assets.d.ts
  frontend/src/types/index.ts
  frontend/tsconfig.json
Labels: 문서, 프론트엔드, 이슈

#271 Fix: 리액트 다운그레이드
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/main.tsx
Labels: 버그, 프론트엔드

#273 Fix: 카드 슬라이더 오른쪽까지 보이도록 수정
  frontend/src/components/Accordion.tsx
  frontend/src/components/Card.tsx
  frontend/src/components/CardSlider.tsx
  frontend/src/components/CommonHeader.tsx
  frontend/src/components/Description.tsx
  frontend/src/components/DetailLocation.tsx
  frontend/src/components/DetailSchedule.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Indexing.tsx
  frontend/src/components/Input.tsx
  frontend/src/components/Item.tsx
  frontend/src/components/LatestSearchSortButton.tsx
  frontend/src/components/LayoutCenter.tsx
  frontend/src/components/LayoutNavigation.tsx
  frontend/src/components/List.tsx
  frontend/src/components/ListTitle.tsx
  frontend/src/components/PopularSearchButton.tsx
  frontend/src/components/SearchCardItem.tsx
  frontend/src/components/SearchCardList.tsx
  frontend/src/components/SearchHeader.tsx
  frontend/src/components/ServiceInfo.tsx
  frontend/src/components/ServiceMenu.tsx
  frontend/src/components/Sidebar/OptionItem/index.tsx
  frontend/src/components/Sidebar/OptionList/index.tsx
  frontend/src/components/Sidebar/index.tsx
  frontend/src/components/TabBar.tsx
  frontend/src/components/TeamInfo.tsx
  frontend/src/components/TodaySubscriptionNull.tsx
  frontend/src/components/UserInfo.tsx
  frontend/src/components/index.ts
  frontend/src/pages/Home.tsx
Labels: 프론트엔드, 유아이

#275 Fix: 2개의 헤더 합치기
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icons/arrowLeft.svg
  frontend/src/assets/icons/hamburger.svg
  frontend/src/components/CommonHeader.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Icon.tsx
  frontend/src/components/LayoutNavigation.tsx
  frontend/src/components/SearchHeader.tsx
  frontend/src/components/index.ts
  frontend/src/pages/Detail.tsx
  frontend/src/pages/Help.tsx
  frontend/src/pages/Like.tsx
  frontend/src/pages/More.tsx
  frontend/src/pages/Mypage.tsx
  frontend/src/pages/Search.tsx
  frontend/src/pages/UserModify.tsx
  frontend/src/types/index.ts
Labels: 프론트엔드, 유아이

#279 Refactor: Backend 코드 Refactoring
  backend/save_my_youth/settings/base.py
  backend/save_my_youth/urls.py
  backend/subscription/api.py
  backend/subscription/schema.py
  backend/user/views.py
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/pages/Login.tsx
  frontend/src/utils/axiosInstance.tsx
Labels: 백엔드

#281 Hotfix: 백엔드 데이터 구조 변경 적용
  frontend/src/hooks/useSubscription.tsx
  frontend/src/pages/Login.tsx
  frontend/src/types/index.ts
Labels: 버그, 핫픽스, 백엔드

#283 Style: 데이터 받아오는 동안 로딩 문구 보여주기
  frontend/src/App.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/LayoutNavigation.tsx
  frontend/src/pages/Home.tsx
Labels: 프론트엔드, 유아이

#285 Hotfix: 빌드 에러 해결
  frontend/src/index.tsx
Labels: 버그

#286 Fix: 로딩 문구 나타나는 조건 변경
  frontend/src/components/CardSlider.tsx
  frontend/src/pages/Home.tsx
Labels: 유아이
